Outputs from lilysplit and ly-files
lilysplit now supports command line attributes and gives colored output
only when needed. The ly-files don't just blurb things out, but use the
appropriate lilypond loglevel settings (which, coincidentally, can be
configured via lilysplit!)

This closes #110

Signed-off-by: Bjørn Bäuchle <baeuchle@frankfurtium.de>

diff --git a/lilysplit b/lilysplit
--- a/lilysplit
+++ b/lilysplit
@@ -1,53 +1,121 @@
 #!/bin/bash
 
+test -t 2; makeColoredOutput=$?;
+loglevel="BASIC"
 includedir="$(dirname $0)"
-if [ -x "$(which lilypond)" ]; then
-    echo ""
+LILYOPTS="--include $includedir"
+LILYEXE="$(which lilypond)"
+GITEXE="$(which git)"
+GITOPT="describe --tags --dirty --always"
+usegit=0 # 0: true, 1: false
+
+while [[ $# -gt 0 ]]; do
+  key="$1"
+  case $key in
+    --color)
+      makeColoredOutput=0;
+      shift;;
+    --nocolor)
+      makeColoredOutput=1;
+      shift;;
+    --loglevel)
+      loglevel=$2A
+      LILYOPTS="$LILYOPTS --loglevel=$2";
+      shift; shift;;
+    --lilyoptions)
+      LILYOPTS="$LILYOPTS $2";
+      shift; shift;;
+    --lilyexe)
+      LILYEXE="$2";
+      shift; shift;;
+    --gitexe)
+      GITEXE="$2";
+      shift; shift;;
+    --gitopt)
+      GITOPT="$2";
+      shift; shift;;
+    --usegit)
+      usegit=0;
+      shift;;
+    --nogit)
+      usegit=1;
+      shift;;
+    --help)
+      echo "Help yourself, I can't, yet."
+      exit 0;;
+    --)
+      shift;
+      break;;
+  esac
+done
+
+####COLORIZE OUTPUT####
+if [[ "$makeColoredOutput" -eq 0 ]]; then # TODO: or --color but not --no-color
+  noColor="\e[0m"
+  headlineColor="\e[1m"
+  versionColor="\e[1;32m"
+  slimVersionColor="\e[4;32m"
+  fileColor="\e[4m"
+  errorColor="\e[1;31m"
+  warningColor="\e[0;31m"
+  progressColor="\e[1;34m"
+  excerptColor="\e[35m"
+fi
+
+if [ -x "$LILYEXE" ]; then
+  true
 else
-    echo "Lilypond not found, please install" >&2
-    exit 1;
+  echo "${headlineColor}lilypond${errorColor} not found, please use $filecolor--lilyexe /path/to/lilypond$noColor" >&2
+  exit 1;
+fi
+if [ $usegit -eq 0 ]; then
+  if [ -x "$GITEXE" ]; then
+    true
+  else
+    echo "${headlineColor}git${warnColor} not found, please use $fileColor--gitexe /path/to/git$warncolor or $fileColor--nogit$noColor" >&2
+    usegit=1
+  fi
 fi
 
 lilyver=""
-if [ -x "$(which git)" ]; then
+if [ $usegit -eq 0 ]; then
     cd $includedir;
-    lilyver="$(git describe --tags --dirty --always)"
+    lilyver="$($GITEXE $GITOPT)"
     lilyver="${lilyver/v/l}"
     cd - >/dev/null
 fi
 
-LILYOPTS=" --include $includedir --loglevel=BASIC "
 nomidi="-dmidi-extension=midirm"
-echo -e "Starting \033[1mlilysplit\033[0m using \033[1;32m$lilyver\033[0m"
+echo -e "Starting ${headlineColor}lilysplit$noColor using $versionColor$lilyver$noColor"
 
 for D in $*; do
     d=${D/.ly/}
     d=$(echo $d | sed 's/\/$//')
     b=$(basename $d)
     # look for version information for each lilypond file separately:
-    if [ -x "$(which git)" ]; then
+    if [ $usegit -eq 0 ]; then
         cd $(dirname $d)
-        version="$(git describe --tags --dirty --always)"
+        version="$($GITEXE $GITOPT)"
         cd - > /dev/null
     else
         version=""
     fi
-    echo -e "Compiling \033[1m$d\033[0m, Version \033[1;32m$version\033[0m"
-    whatwedoinfo="(\033[4m$d\033[0m \033[4;32m$version $lilyver\033[0m)"
+    echo -e "Compiling $headlineColor$d$noColor, Version $versionColor$version$noColor"
+    whatwedoinfo="($fileColor$d$noColor $slimVersionColor$version $lilyver$noColor)"
     # Normale Version:
     # (wir löschen später alles, was mit midirm aufhört)
-    echo -e "\033[1;34mComplete Score\033[0m $whatwedoinfo"
-    lilypond $LILYOPTS $nomidi -e "(begin (define lilyver \"$lilyver\") (define gitver \"$version\"))" $d.ly;
+    echo -e "${progressColor}Complete Score$noColor $whatwedoinfo"
+    $LILYEXE $LILYOPTS $nomidi -e "(begin (define lilyver \"$lilyver\") (define gitver \"$version\"))" $d.ly;
     if [ $? -eq 1 ]; then
-      echo -e "\033[1;31mCompilation failed!\033[0m"
+      echo -e "${errorColor}Compilation failed!$noColor"
       continue;
     fi
     mv $b-.pdf $b.pdf
     # MIDI-Version (wir löschen nachher auch das ps)
-    echo -e "\033[1;34mMidi Version\033[0m $whatwedoinfo"
-    lilypond $LILYOPTS --ps -dmidi-extension=midi -e "(begin (define lilyver \"$lilyver\") (define gitver \"$version\") (define makeMidi #t))" $d.ly;
+    echo -e "${progressColor}Midi Version$noColor $whatwedoinfo"
+    $LILYEXE $LILYOPTS --ps -dmidi-extension=midi -e "(begin (define lilyver \"$lilyver\") (define gitver \"$version\") (define makeMidi #t))" $d.ly;
     if [ $? -eq 1 ]; then
-      echo -e "\033[1;31mCompilation failed!\033[0m"
+      echo -e "${errorColor}Compilation failed!$noColor"
       continue;
     fi
     mv $b-midi.midi $b.midi
@@ -57,14 +125,14 @@ for D in $*; do
         has="has${namen[$s]}";
         show="show${namen[$s]}";
         if [ "$(grep -q $has $d.ly; echo $?)" == "0" ]; then
-            echo -e "\033[1;34mExcerpt $s\033[0m: \033[0;32m${namen[$s]}\033[0m $whatwedoinfo"
-            lilypond $LILYOPTS $nomidi -e "(begin (define lilyver \"$lilyver\") (define gitver \"$version\") (define showAlle #f) (define $show #t))" "$d.ly";
+            echo -e "${progressColor}Excerpt $s$noColor: $excerptColor${namen[$s]}$noColor $whatwedoinfo"
+            $LILYEXE $LILYOPTS $nomidi -e "(begin (define lilyver \"$lilyver\") (define gitver \"$version\") (define showAlle #f) (define $show #t))" "$d.ly";
             if [ $? -eq 1 ]; then
-              echo -e "\033[1;31mCompilation failed!\033[0m"
+              echo -e "${errorColor}Compilation failed!$noColor"
               break;
             fi
         else
-            echo -e "\033[31mNo excerpt $s\033[0m: \033[0;35m${namen[$s]}\033[0m"
+            echo -e "${warningColor}No excerpt $s$noColor: $excerptColor${namen[$s]}$noColor"
         fi;
     done;
     rm $b*midirm;
